name: run main.py

on:
  schedule:
    - cron: '*/1 * * * *'  # Every minute

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3  # Use the latest version to avoid Node.js deprecation issues

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update log.txt" || echo "No changes to commit"

      - name: push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
